name: Build
description: 🏗️ GitHub Action for building and publishing Docker images to GitHub.

inputs:
  github-token:
    description: Used for publishing to GitHub Packages.
    required: true

  dockerfile:
    description: Path to the Dockerfile.
    required: true

  image:
    description: The name of the image to build.
    required: true

  tag:
    description: The tag to apply to the built image.
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: saturdayshdev
        password: ${{ inputs.github-token }}

    - name: Build & Publish
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        tags: ghcr.io/saturdayshdev/${{ inputs.image }}:${{ inputs.tag }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
